# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-21 17:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment163',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.IntegerField(blank=True, null=True, verbose_name='主标题')),
                ('txt', models.TextField(blank=True, null=True, verbose_name='评论')),
                ('author', models.CharField(blank=True, max_length=5000, null=True, verbose_name='author')),
                ('liked', models.IntegerField(blank=True, null=True, verbose_name='评论数')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url1', models.CharField(max_length=200, verbose_name='链接')),
                ('url1_txt', models.CharField(default='内容XXXX', max_length=100, verbose_name='标题')),
                ('content', models.CharField(default='内容XXXX', max_length=200, verbose_name='内容')),
                ('more_url', models.CharField(default='#', max_length=200, verbose_name='More')),
                ('icon', models.CharField(default='icon1', max_length=30, verbose_name='样式')),
                ('more_txt', models.CharField(default='More', max_length=30, verbose_name='More_txt')),
                ('addtime', models.DateTimeField(default=datetime.datetime(2019, 1, 21, 17, 26, 6, 546472), verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '四模块',
                'verbose_name_plural': '四模块',
            },
        ),
        migrations.CreateModel(
            name='Img_txt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt1', models.CharField(max_length=500, verbose_name='主标题')),
                ('txt2', models.CharField(max_length=200, verbose_name='副标题')),
                ('txt3', models.CharField(max_length=50, verbose_name='跳转标题')),
                ('url', models.CharField(max_length=30, verbose_name='链接')),
                ('addtime', models.DateTimeField(default=datetime.datetime(2019, 1, 21, 17, 26, 6, 547623), verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '图片下标题',
                'verbose_name_plural': '图片下标题',
            },
        ),
        migrations.CreateModel(
            name='Index_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(default=datetime.datetime(2019, 1, 21, 17, 26, 6, 546948), verbose_name='添加时间')),
                ('img', models.ImageField(upload_to='index_img/', verbose_name='轮播图')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Lyric163',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.IntegerField(blank=True, null=True, verbose_name='song_id')),
                ('txt', models.TextField(blank=True, null=True, verbose_name='txt ')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='create_time')),
            ],
            options={
                'verbose_name': '歌词',
                'verbose_name_plural': '歌词',
            },
        ),
        migrations.CreateModel(
            name='Music163',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.IntegerField(blank=True, null=True, verbose_name='歌曲ID')),
                ('song_name', models.CharField(blank=True, max_length=5000, null=True, verbose_name='song_name')),
                ('author', models.CharField(blank=True, max_length=5000, null=True, verbose_name='author')),
                ('playtime', models.IntegerField(blank=True, db_column='playTime', null=True, verbose_name='playtime')),
                ('done', models.CharField(blank=True, max_length=255, null=True, verbose_name='done')),
                ('has_lyric', models.CharField(blank=True, max_length=255, null=True, verbose_name='has_lyric')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='create_time')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='update_time')),
                ('comment', models.IntegerField(blank=True, null=True, verbose_name='comment')),
            ],
            options={
                'verbose_name': '音乐',
                'verbose_name_plural': '音乐',
            },
        ),
        migrations.CreateModel(
            name='Netnew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Tst', max_length=50, verbose_name='标题')),
                ('title1', models.CharField(default='Tst', max_length=150, verbose_name='标题内容')),
                ('txt', models.CharField(default='txt', max_length=500, verbose_name='评论内容')),
                ('name', models.CharField(default='周杰伦', max_length=30, verbose_name='姓名')),
                ('song', models.CharField(default='听妈妈的话', max_length=30, verbose_name='歌曲')),
                ('song_txt', models.CharField(default='5300', max_length=30, verbose_name='评论数')),
                ('addtime', models.DateTimeField(default=datetime.datetime(2019, 1, 21, 17, 26, 6, 544370), verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '网易评论',
                'verbose_name_plural': '网易评论',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='person_img/', verbose_name='个人图')),
                ('more_txt', models.CharField(default='更多', max_length=100, verbose_name='more_txt')),
                ('title', models.CharField(default='Tst', max_length=50, verbose_name='标题')),
                ('txt', models.CharField(default='txt', max_length=50, verbose_name='内容')),
                ('more_url', models.CharField(default='#', max_length=30, verbose_name='more_url')),
                ('addtime', models.DateTimeField(default=datetime.datetime(2019, 1, 21, 17, 26, 6, 544934), verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '个人',
                'verbose_name_plural': '个人',
            },
        ),
        migrations.CreateModel(
            name='Playlist163',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=5000, null=True, verbose_name='title')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='link')),
                ('cnt', models.IntegerField(blank=True, null=True, verbose_name='cnt')),
                ('playcount', models.IntegerField(blank=True, db_column='playCount', null=True, verbose_name='playcount')),
                ('sharecount', models.IntegerField(blank=True, db_column='shareCount', null=True, verbose_name='sharecount')),
                ('commentcount', models.IntegerField(blank=True, db_column='commentCount', null=True, verbose_name='commentcount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='tags')),
                ('dsc', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('done', models.CharField(blank=True, max_length=255, null=True, verbose_name='完成')),
            ],
            options={
                'verbose_name': '歌曲列表',
                'verbose_name_plural': '歌曲列表',
            },
        ),
        migrations.CreateModel(
            name='Portfolie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='portfolie_img/', verbose_name='个人图')),
                ('h2_title', models.CharField(default='Tst', max_length=50, verbose_name='图片标题')),
                ('div_url', models.CharField(default='#', max_length=30, verbose_name='div链接')),
                ('p_txt', models.CharField(default='txt', max_length=500, verbose_name='图片文字')),
                ('readmore', models.CharField(default='点击READMORE', max_length=30, verbose_name='更多')),
                ('readmore_url', models.CharField(default='#', max_length=30, verbose_name='更多链接')),
                ('addtime', models.DateTimeField(default=datetime.datetime(2019, 1, 21, 17, 26, 6, 543623), verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '产品轮播',
                'verbose_name_plural': '产品轮播',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Test', max_length=30, verbose_name='标题')),
                ('addtime', models.DateTimeField(default=datetime.datetime(2019, 1, 21, 17, 26, 6, 545728), verbose_name='添加时间')),
                ('class_blank', models.CharField(choices=[('_blank', '跳出本页'), ('_self', '本页跳转')], default='_blank', max_length=10, verbose_name='跳转')),
                ('url', models.CharField(default='#', max_length=300, verbose_name='链接')),
            ],
            options={
                'verbose_name': '标题表',
                'verbose_name_plural': '标题表',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_browser', models.CharField(default='txt', max_length=300, verbose_name='浏览器')),
                ('visit_page', models.CharField(default='index', max_length=30, verbose_name='访问页')),
                ('visit_ip', models.CharField(default='192.168.1.1', max_length=30, verbose_name='访问IP')),
                ('visit_time', models.DateTimeField(default=datetime.datetime(2019, 1, 21, 17, 26, 6, 542869), verbose_name='访问时间')),
                ('visit_address', models.CharField(default='武汉', max_length=180, verbose_name='访问地址')),
            ],
            options={
                'verbose_name': '访问记录',
                'verbose_name_plural': '访问记录',
            },
        ),
    ]
