# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-21 17:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_msg',
            field=models.CharField(default='msg', max_length=200, verbose_name='访问信息'),
        ),
        migrations.AlterField(
            model_name='content',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 17, 36, 19, 26449), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='img_txt',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 17, 36, 19, 31805), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='index_img',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 17, 36, 19, 26870), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='netnew',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 17, 36, 19, 24412), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='person',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 17, 36, 19, 24979), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='portfolie',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 17, 36, 19, 22493), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='title',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 17, 36, 19, 25751), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 17, 36, 19, 21653), verbose_name='访问时间'),
        ),
    ]
